DROP TABLE IF EXISTS MigrationsHistory;

CREATE TABLE MigrationsHistory (ID INTEGER PRIMARY KEY AUTOINCREMENT
, ScriptName TEXT
, DateExecuted TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO MigrationsHistory (ScriptName)
SELECT 'db-init.sql';

DROP TABLE IF EXISTS Apps;
DROP TABLE IF EXISTS Forms;
DROP TABLE IF EXISTS Controls;
DROP TABLE IF EXISTS Fields;
DROP TABLE IF EXISTS SqlCommands;
DROP TABLE IF EXISTS ControlsSources;

CREATE TABLE Apps (ID INTEGER PRIMARY KEY AUTOINCREMENT
,AppName TEXT NOT NULL 
,DateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Forms(ID INTEGER PRIMARY KEY AUTOINCREMENT
,FormName TEXT NOT NULL 
,ID_Apps INTEGER NOT NULL REFERENCES Apps(ID)
,ID_Forms_Parent NULL REFERENCES Forms(ID)
,DateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER IF NOT EXISTS Forms_AFTER_INSERT AFTER INSERT ON Forms WHEN (NEW.ID = NEW.ID_Forms_Parent)
BEGIN
    RAISE(ROLLBACK,'Form cannot be its own parent.');
END;

CREATE TRIGGER IF NOT EXISTS Forms_BEFORE_UPDATE BEFORE UPDATE ON Forms WHEN (NEW.ID = NEW.ID_Forms_Parent)
BEGIN
    RAISE(ROLLBACK,'Form cannot be its own parent.');
END;

CREATE TABLE ControlTypes (ID INTEGER PRIMARY KEY AUTOINCREMENT
,Name TEXT NOT NULL 
,Value TEXT NOT NULL 
,DateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Controls(ID INTEGER PRIMARY KEY AUTOINCREMENT
,ControlName TEXT NOT NULL 
,ID_Forms INTEGER NOT NULL REFERENCES Forms(ID)
,ID_ControlTypes INTEGER NOT NULL REFERENCES ControlTypes(ID)
,DateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE FieldTypes (ID INTEGER PRIMARY KEY AUTOINCREMENT
,Name TEXT NOT NULL 
,Value TEXT NOT NULL 
,DateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Fields(ID INTEGER PRIMARY KEY AUTOINCREMENT
,FieldName TEXT NOT NULL
,Label TEXT
,ID_Controls INTEGER NOT NULL REFERENCES Forms(ID)
,ID_FieldTypes INTEGER NOT NULL REFERENCES FieldTypes(ID)
,DateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SqlCommands(ID INTEGER PRIMARY KEY AUTOINCREMENT
,Command TEXT NOT NULL
,ID_FieldTypes INTEGER NOT NULL REFERENCES FieldTypes(ID)
,DateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE ParameterTypes (ID INTEGER PRIMARY KEY AUTOINCREMENT
,Name TEXT NOT NULL 
,Value TEXT NOT NULL 
,DateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE SqlCommandParameters(ID INTEGER PRIMARY KEY AUTOINCREMENT
,ID_SqlCommands INTEGER NOT NULL REFERENCES SqlCommands(ID)
,ParameterKey TEXT NOT NULL 
,ID_ParameterTypes INTEGER NOT NULL  REFERENCES ParameterTypes(ID)
)
CREATE TABLE ControlCommandTypes (ID INTEGER PRIMARY KEY AUTOINCREMENT
,Name TEXT NOT NULL 
,Value TEXT NOT NULL 
,DateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ControlSqlCommands(ID INTEGER PRIMARY KEY AUTOINCREMENT
,ID_Controls INTEGER NOT NULL REFERENCES Controls(ID)
,ID_SqlCommands INTEGER NOT NULL REFERENCES SqlCommands(ID)
,ID_ControlCommandTypes INTEGER NOT NULL REFERENCES ControlCommandTypes(ID)
)

