DROP TABLE IF EXISTS MigrationsHistory;

CREATE TABLE MigrationsHistory (ID INTEGER PRIMARY KEY AUTOINCREMENT
, ScriptName TEXT
, DateExecuted TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO MigrationsHistory (ScriptName)
SELECT 'db-init.sql';



DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Roles;


CREATE TABLE Users (
    ID INTEGER PRIMARY KEY AUTOINCREMENT, 
    UserLogin Text UNIQUE,
    DateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DateModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP   
    );

CREATE TABLE Roles (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT,
     DateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ID_Users_Creator INTEGER NOT NULL REFERENCES Users(ID),
    DateModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ID_Users_Modified INTEGER REFERENCES Users(ID)   
    );

